name: Flutter Web Build and Deploy to FTP

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # Checkout the repository content to the GitHub Actions runner

    - uses: subosito/flutter-action@v1  # Setup Flutter environment
      with:
        flutter-version: '3.13.7' # Specify the Flutter version you want to use

    - name: Install Flutter Dependencies  # Install dependencies specified in pubspec.yaml
      run: flutter pub get

    - name: Enable Flutter Web  # Enable Flutter for web development
      run: flutter config --enable-web

    - name: Build Flutter Web App  # Build the Flutter project for web
      run: flutter build web

    - name: Deploy to FTP Server  # Deploy the build to the FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: 149.255.58.70
        username: drips
        password: "!8M9ose36"
        local-dir: build/web/
        # Since you are deploying to the root directory and using unencrypted FTP, no need to specify server-dir or encryption settings

