name: Flutter Web Build and Push to Branch

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # Checkout the repository content to the GitHub Actions runner

    - uses: subosito/flutter-action@v1  # Setup Flutter environment
      with:
        flutter-version: '3.13.7'  # Specify the Flutter version you want to use

    - name: Install Flutter Dependencies  # Install dependencies specified in pubspec.yaml
      run: flutter pub get

    - name: Enable Flutter Web  # Enable Flutter for web development
      run: flutter config --enable-web

    - name: Build Flutter Web App  # Build the Flutter project for web
      run: flutter build web

    - name: Checkout target branch  # Checkout the target branch to push changes to
      uses: actions/checkout@v2
      with:
        ref: "target-branch"
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Copy build/web to root  # Copy the build/web directory to the root of the working directory
      run: |
        rm -rf *  # Clear the current content (be careful with this command)
        cp -r build/web/* .  # Copy the build/web contents to the root

    - name: Commit and push changes  # Commit and push the changes to the target branch
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Deploy Flutter web build to target branch" || echo "No changes to commit"
        git push origin HEAD:"target-branch"  # Push changes to the target branch
