name: Flutter Web Build and Push to Live Branch

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # Checkout the repository content to the GitHub Actions runner with full history
      with:
        fetch-depth: 0

    - uses: subosito/flutter-action@v1  # Setup Flutter environment
      with:
        flutter-version: '3.13.7'

    - name: Install Flutter Dependencies  # Install dependencies specified in pubspec.yaml
      run: flutter pub get

    - name: Enable Flutter Web
      run: flutter config --enable-web

    - name: Build Flutter Web App  # Build the Flutter project for web
      run: flutter build web

    - name: Commit and Push Build to Live Branch
      uses: EndBug/add-and-commit@v7
      with:
        author_name: GitHub Actions
        author_email: actions@github.com
        message: 'Deploy Flutter web build to live'
        add: 'build/web/*'
        cwd: 'build/web'
        pull_strategy: 'NO-PULL' # Do not pull the branch before pushing
        push: true
        target_branch: 'live' # The branch to push the built web app to
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
